version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_dock
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: forum 
    ports:
      - "5432:5432"
    networks:
      - global-network
  
networks:
  global-network:
    external: true 

    
